In [1]:
import numpy as np
np.__version__

'1.21.5'

# create an 1d array using array function

In [2]:
a = np.array([1,2,3,4,5])
print(a.dtype)
print(a.shape)

int32
(5,)


# create 1d array using arange function

In [3]:
arr = np.arange(10)
print(arr)
print(arr.dtype)
print(arr.shape)

[0 1 2 3 4 5 6 7 8 9]
int32
(10,)


# create 2d array using array

In [4]:
b = np.array([[1,2,3,],[4,5,6]])
print(b)
print(b.dtype)
print(b.shape)

[[1 2 3]
 [4 5 6]]
int32
(2, 3)


# create 2d array using arange function

In [5]:
c = np.arange(18).reshape(6,3)
print(c)
print(c.dtype)
print(c.shape)

[[ 0  1  2]
 [ 3  4  5]
 [ 6  7  8]
 [ 9 10 11]
 [12 13 14]
 [15 16 17]]
int32
(6, 3)


# create 3d array using array function

In [6]:
d =np.array(
    [
    [[1,2,3],[2,3,4]],
    [[3,4,5],[4,5,6]],
    [[5,6,7],[6,7,8]]
    ]
)
print(d)
print(d.dtype)
print(d.shape)
print(d.size)

[[[1 2 3]
  [2 3 4]]

 [[3 4 5]
  [4 5 6]]

 [[5 6 7]
  [6 7 8]]]
int32
(3, 2, 3)
18


# create 3d array using arange function

In [7]:
e = np.arange(18).reshape(3,2,3)
print(e)
print(e.dtype)
print(e.shape)
print(e.size)

[[[ 0  1  2]
  [ 3  4  5]]

 [[ 6  7  8]
  [ 9 10 11]]

 [[12 13 14]
  [15 16 17]]]
int32
(3, 2, 3)
18


# Createing array using zeros

In [8]:
f = np.zeros(50).reshape(5,10)
print(f)
print(f.dtype)
print(f.shape)
print(f.size)


[[0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]]
float64
(5, 10)
50


# Createing array using ones

In [9]:
g = np.ones(10).reshape(2,5)
print(g)
print(g.dtype)
print(g.shape)
print(g.size)

[[1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]]
float64
(2, 5)
10


# Createing  ones using 2D array

In [10]:
g = np.ones((4,2),dtype=np.int64)
g


array([[1, 1],
       [1, 1],
       [1, 1],
       [1, 1]], dtype=int64)

# Createing ones using 3D array

In [11]:
g =np.ones((3,2,3),dtype=np.int32)
g

array([[[1, 1, 1],
        [1, 1, 1]],

       [[1, 1, 1],
        [1, 1, 1]],

       [[1, 1, 1],
        [1, 1, 1]]])

# creating random numbers using 1d array

In [12]:
h = np.random.randint(1,3,size=(10))
print(h)
print(h.dtype)
print(h.shape)

[1 2 2 1 1 1 1 1 2 1]
int32
(10,)


# creating random numbers using 2d array

In [13]:
i =np.random.randint(1,5,size =(5,5))
print(i)
print(i.dtype)
print(i.shape)

[[4 4 3 2 1]
 [4 1 1 3 1]
 [4 3 3 2 1]
 [4 4 2 2 3]
 [2 1 2 4 4]]
int32
(5, 5)


# creating random numbers using 3d array

In [14]:
j =np.random.randint(1,10,size=(3,3,3))
print(j)
print(j.dtype)
print(j.shape)

[[[2 5 1]
  [4 6 4]
  [3 3 6]]

 [[7 7 7]
  [3 3 5]
  [2 8 5]]

 [[7 3 5]
  [1 8 8]
  [4 3 4]]]
int32
(3, 3, 3)


# create array with single low multipal high

In [15]:
k =np.random.randint(5,[10,20,30,40,50])
print(k)
print(k.dtype)
print(k.shape)

[ 9 15 21 16 37]
int32
(5,)


# create array with single high multipal low

In [16]:
l =np.random.randint([10,20,30,40],50)
print(l)
print(l.dtype)
print(l.shape)


[20 25 45 47]
int32
(4,)


# create array with multipal low mulyipal high

In [17]:
m =np.random.randint([1,2,3],[10,20,30])
print(m)
print(m.dtype)
print(m.shape)

[ 1  8 14]
int32
(3,)


# random.randn function 1D

In [18]:
n = np.random.randn(3)
n

array([ 1.9752215 ,  1.4324732 , -1.16214567])

# random.randn function 2D

In [19]:
o =np.random.randn(3,3)
print(o)
print(o.dtype)
print(o.shape)
print(o.size)

[[ 0.82381118 -0.74466435 -1.30416492]
 [-0.13913472  0.57299234 -0.57570272]
 [-0.4174876   0.1382561  -0.77485866]]
float64
(3, 3)
9


# random.randn function 3D

In [20]:
p =np.random.randn(3,3,3)
print(p)
print(p.dtype)
print(p.shape)
print(p.size)

[[[-0.42315546 -0.78665566  0.68140253]
  [ 0.20730194  0.78755718  1.90139114]
  [ 1.38236423  0.45723964 -0.75171245]]

 [[ 0.21392073  1.5470621   1.58718551]
  [-0.37246665 -0.47288487  0.41305759]
  [ 0.46965877  0.29137044 -1.72678221]]

 [[-0.16046344  1.00016985 -0.56307927]
  [-2.30225889 -0.49591842  0.55739008]
  [ 0.26279243 -0.91619915 -1.14481045]]]
float64
(3, 3, 3)
27


# creating rand function

In [21]:
q =np.random.rand(10)
print(q)
print(q.shape)
print(q.dtype)
print(q.size)

[0.43349204 0.67857179 0.48109234 0.81403015 0.37918077 0.16448655
 0.02881222 0.134684   0.1121328  0.5465478 ]
(10,)
float64
10


# creating array positive indexing

In [22]:
r =np.array([1,2,3,4])
print(r[3])

4


# creating array positive indexing 2D

In [23]:
r =np.array([[1,2,3,4],[5,6,7,8]])
print(r[1,0])
print(r[0,2])

5
3


# creating array positive indexing 3D

In [24]:
r =np.array(
    [
        [[1,2,3],[2,3,4]],
        [[3,4,5],[4,5,6]],
        [[5,6,7],[6,7,8]]
    ]
)
print(r[0,1,0])
print(r[1,1,2])

2
6


# creating array negative indexing 1D

In [25]:
s =np.array([1,2,3,4,5])
print(s[-2])

4


# creating array negative indexing 2D

In [26]:
s =np.array([[1,2,3,4],[5,6,7,8]])
print(s[-1,-1])
print(s[-2,-3])

8
2


# creating array negative indexing 3D

In [27]:
s =np.array([[[1,2,3],[2,3,4]],[[3,4,5],[4,5,6]],[[5,6,7],[6,7,8]]])
print(s[-1,-1,-3])
print(s[-1,-2,-1])
print(s[-3,-1,-1])

6
7
4


# numpy array slicing

# slice elements from index 1to index 5 from the folling array

In [28]:
        #    0 1 2 3 4 5   
t =np.array([1,2,3,4,5,6])
print(t[1:5])

[2 3 4 5]


# slice elements from index 4to end array


In [29]:
        #    0 1 2 3 4 5 6
t =np.array([1,2,3,4,5,6,7])
print(t[4:7])

[5 6 7]


# slice elements from start to index 4 (not include)

In [30]:
#            0 1 2 3 4
t =np.array([1,2,3,4,5])
print(t[:4])

[1 2 3 4]


# negative slicing

slice from index 3 from end of to index 1 from end


In [31]:
 #           7 6 5 4 3 2 1
u =np.array([1,2,3,4,5,6,7])
print(u[-3:-1])

[5 6]


return every eliments from index 1 to index 5

In [32]:
u =np.array([1,2,3,4,5,6,7])
print(u[-1:-5:-2])

[7 5]


return every outher elements from the entire array

In [33]:
u =np.array([1,2,3,4,5,6,7])
print(u[::3])

[1 4 7]


# slicing 2d array

from second element from index 1 to index 4 (not included)

In [34]:
v =np.array([[1,2,3,4,5],[6,7,8,9,10]])
print(v[1,1:4])
print(v[0,0:4])

[7 8 9]
[1 2 3 4]


# from both array return index 2

In [35]:
v =np.array([[1,2,3,4,5],[6,7,8,9,10]])
print(v[0:2,1:4])

[[2 3 4]
 [7 8 9]]


# Numpy array copy & view

In [36]:
#copy
w =np.array([1,2,3,4,5])
w1 =np.copy(w)
w1[1]=7
w[0]=6
print(w)
print(w1)




[6 2 3 4 5]
[1 7 3 4 5]


In [37]:
#view
x =np.array([1,2,3,4,5])
x1 =x.view()
x[0]=6
print(x)
print(x1)


[6 2 3 4 5]
[6 2 3 4 5]


# Reshapeing Function

In [38]:
y =np.array([1,2,3,4,5,6,7,8,9,10,11,12])
print("Orginal Array:")
print(y)
y1 =y.reshape(4,3) #2D
print("\nArray dimensions (4,2)")
print(y1)
y2 =y.reshape(2,3,2)#3D
print("\nArray dimensions (2,3,2)")
print(y2)


Orginal Array:
[ 1  2  3  4  5  6  7  8  9 10 11 12]

Array dimensions (4,2)
[[ 1  2  3]
 [ 4  5  6]
 [ 7  8  9]
 [10 11 12]]

Array dimensions (2,3,2)
[[[ 1  2]
  [ 3  4]
  [ 5  6]]

 [[ 7  8]
  [ 9 10]
  [11 12]]]


# Sum Function

In [39]:
z =np.array([10,20,30,40])
print(z)
print(np.sum(z))

[10 20 30 40]
100


In [40]:
z1=np.array([[1,2,3,4],[2,3,4,5]])
print("Orginal Array:")
print(z1)

print("\n sum axis 0")
print(np.sum(z1,axis=0))

print("\n sum axis 1")
print(np.sum(z1,axis=1))



Orginal Array:
[[1 2 3 4]
 [2 3 4 5]]

 sum axis 0
[3 5 7 9]

 sum axis 1
[10 14]


# Mean Function

In [41]:
a1 = np.array([1,2,3,4])
print(np.mean(a1))


a2 =np.array([[1,2,3,4],[2,3,4,5]])
print(np.mean(a2))



2.5
3.0


In [42]:
a1=np.array([[1,2,3,4],[2,3,4,5]])
print("Orginal Array:")
print(a1)

print("\n mean axis 0")
print(np.mean(a1,axis=0))

print("\n maean axis 1")
print(np.mean(a1,axis=1))

Orginal Array:
[[1 2 3 4]
 [2 3 4 5]]

 mean axis 0
[1.5 2.5 3.5 4.5]

 maean axis 1
[2.5 3.5]


# Std Function

In [48]:
a2 =np.array([[1,2],[3,4]])
print("std org")
print(np.std(a2))
print("\nstd axis 0")
print(np.std(a2,axis=0))
print("\nstd axis 1")
print(np.std(a2,axis=1))




std org
1.118033988749895

std axis 0
[1. 1.]

std axis 1
[0.5 0.5]


# Var Function

In [49]:
a3 =np.array([[1,2],[3,4]])
print("var org")
print(np.var(a3))
print("\nvar axis 0")
print(np.var(a3,axis=0))
print("\nvar axis 1")
print(np.var(a3,axis=1))

var org
1.25

var axis 0
[1. 1.]

var axis 1
[0.25 0.25]


# Min Function

In [50]:
a4 =np.array([[1,2],[3,4]])
print("min org")
print(np.min(a4))
print("\nmin axis 0")
print(np.min(a4,axis=0))
print("\nvar axis 1")
print(np.min(a4,axis=1))

min org
1

min axis 0
[1 2]

var axis 1
[1 3]


# max Function

In [51]:
a5 =np.array([[1,2],[3,4]])
print("max org")
print(np.max(a3))
print("\nmax axis 0")
print(np.max(a3,axis=0))
print("\nmax axis 1")
print(np.max(a3,axis=1))

max org
4

max axis 0
[3 4]

max axis 1
[2 4]
